#!/usr/bin/env python3

import csv

def read_employees(csv_file_location):
    employee_list = []
    with open(csv_file_location) as file:
        csv.register_dialect('empDialect', skipinitalspace=True, strict=True)
        reader = csv.DictReader(file, dialect = 'empDialect')
        for data in reader:
            employee_list.append(data)
    return employee_list
    
def process_data(employee_list):
    department_list = []
    for employee_data in employee_list:
        department_list.append(employee_data['Department'])
    
    department_data = {}
    for department_name in set(deparment_list):
        department_data[department_name] = department_list.count(department_name)
        
def write_report(dictionary, report_file):
    with open(report_file, "w+") as f:
        for k in sorted(dictionary):
            f.write(str(k)+':'+str(dictionary[k]+'\n')
        f.close()
        
employee_list = read_employees('/home/student-04-1d1999e69545/data/employees.csv')
dictionary = process_data(employee_list)
write_report(dictionary,'/home/student-04-1d1999e69545/test_report.txt')
